name: "Prep"

on: [workflow_call]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install latest Cranko
        run: |
          d="$(mktemp -d /tmp/cranko.XXXXXX)"
          cd "$d"
          curl --proto '=https' --tlsv1.2 -sSf https://pkgw.github.io/cranko/fetch-latest.sh | sh
          echo "PATH=$d:$PATH" >> "$GITHUB_ENV"
      - name: "Checkout Branch"
        run: |
          git fetch --tags --force origin
          if [[ "${{ github.ref_type }}" == "branch" ]]; then
            git checkout -B ${{ github.ref_name }}
            git branch --set-upstream-to=origin/${{ github.ref_name }} ${{ github.ref_name }}
          fi
          git tag -l
      - name: "cranko release-workflow apply-versions"
        run: cranko release-workflow apply-versions
        env:
          CRANKO_HEAD_BRANCH: ${{ github.ref_name }}
      - name: "Mini-build to freshen Cargo.lock"
        run: cargo build -p tectonic_cfg_support
      - name: Generate release commit
        run: |
          git add .
          cranko release-workflow commit
          git show
        env:
          CRANKO_HEAD_BRANCH: ${{ github.ref_name }}
      - name: Generate git bundle
        run: |
          git bundle create release.bundle HEAD
      - name: Publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-bundle
          path: release.bundle